### ISSUE TITLE
TypeError: source.getFullText is not a function

### ISSUE THREAD

**Issue by draganrakas** [durad/tscover#5]
Node version: 9.4.0

Command used: `tscover -p tsconfig.json`

Not sure if this repo is maintained anymore, but running `tscover` to build our codebase (`tsc` works without issue) produces this stacktrace:

```/usr/local/lib/node_modules/tscover/build/util.js:15
            hash.update(source.getFullText());
                               ^

TypeError: source.getFullText is not a function
    at Function.Util.calculateHash (/usr/local/lib/node_modules/tscover/build/util.js:15:32)
    at Object.ts.createProgram (/usr/local/lib/node_modules/tscover/build/project.js:46:38)
    at performCompilation (evalmachine.<anonymous>:73788:26)
    at Object.executeCommandLine (evalmachine.<anonymous>:73721:17)
    at ProjectInstrumenter.run (/usr/local/lib/node_modules/tscover/build/project.js:64:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/tscover/build/index.js:4:37)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)```

**Comment by durad** [comment]
Working on new version that will address this.
